### ISSUE TITLE
the demo site  is not accesable 

### ISSUE THREAD

**Issue by botanyzh** [smpallen99/ex_admin_demo#5]
i m pretty new to the framework but  the veteran  in our tech communicate  group also can't make it accesable as the demo shows

i dont know if it  is ecto's problem that the scheme in the postgresql   can't been create ,that is the mix ecto.migrate doesn't make sense, so in the runtime the error shows 

![20160921132429](https://cloud.githubusercontent.com/assets/8335153/18698696/cba4e976-7ffe-11e6-99b6-f29c1a55ef53.jpg)

**Comment by smpallen99** [comment]
Please provide the full exception from the console.

**Comment by botanyzh** [comment]
## **here is the the full exception from the console when opening the page "http://localhost:4002/admin"**

PS D:\pheonixWeb\ex_admin_demo-master> mix phoenix.server
[warn] using the :root endpoint configuration for watchers is deprecated.
Pass the :cd option at the end of your watcher argument list in config/dev.exs. For example:

```
watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin",
           cd: Path.expand("../", __DIR__)]]
```

[info] Running ExAdminDemo.Endpoint with Cowboy using http://localhost:4002
22 Sep 10:51:51 - info: compiled 10 files into 2 files, copied 22 in 2.7 sec
[info] GET /admin
[debug] Processing by ExAdmin.AdminController.dashboard/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] QUERY ERROR db=0.0ms
SELECT o0."id", o0."checked_out_at", o0."total_price", o0."user_id", o0."inserted_at", o0."updated_at" FROM "orders" AS
o0 WHERE (NOT (o0."checked_out_at" IS NULL)) LIMIT $1 [5]
[error] %Postgrex.Error{connection_id: 10596, message: nil, postgres: %{code: :undefined_table, file: "parse_relation.c"
, line: "1159", message: "relation \"orders\" not exist", pg_code: "42P01", position: "109", routine: "parserOpenTable", severity: "
error", unknown: "ERROR"}}
[error] 
[
{Ecto.Adapters.SQL, :execute_and_cache, 7, [file: 'lib/ecto/adapters/sql.ex', line: 405]}, 
{Ecto.Repo.Queryable, :execute, 5, [file: 'lib/ecto/repo/queryable.ex', line: 127]}, 
{Ecto.Repo.Queryable, :all, 4, [file: 'lib/ecto/repo/queryable.ex', line: 40]}, 
{ExAdminDemo.ExAdmin.Dashboard, :page_view, 1, [file: 'lib/ex_admin/page.ex', line: 14]}, 
{ExAdmin.AdminController, :dashboard, 2, [file: 'web/controllers/admin_controller.ex', line: 13]}, 
{ExAdmin.AdminController,:action, 2, [file: 'web/controllers/admin_controller.ex', line: 1]}, 
{ExAdmin.AdminController, :phoenix_controller_pipel
ine, 2, [file: 'web/controllers/admin_controller.ex', line: 1]}, 
{ExAdminDemo.Endpoint, :instrument, 4, [file: 'lib/ex_admin_demo/endpoint.ex', line: 1]}, 
{ExAdminDemo.Router, :dispatch, 2, [file: 'lib/phoenix/router.ex', line: 261]}, 
{ExAdminDemo.Router, :do_call, 2, [file: 'web/router.ex', line: 1]},
{ExAdminDemo.Endpoint, :phoenix_pipeline, 1, [file: 'lib/ex_admin_demo/endpoint.ex', line: 1]}, 
{ExAdminDemo.Endpoint, :"call (overridable 3)", 2, [file: 'lib/plug/debugger.ex', line: 93]},
{ExAdminDemo.Endpoint, :call, 2, [file: 'lib/ex_admin_demo/endpoint.ex', line: 1]}, 
{Plug.Adapters.Cowboy.Handler, :upgrade, 4, [file: 'lib/plug/adapters/cowboy/handler.ex', line: 15]}, 
{:cowboy_protocol, :execute, 4, [file: 'src/cowboy_protocol.erl', line: 442]}
]
[error] %Postgrex.Error{connection_id: 10596, message: nil, postgres: %{code: :undefined_table, file: "parse_relation.c"
, line: "1159", message: "relation \"orders\" not exist", pg_code: "42P01", position: "109", routine: "parserOpenTable", severity: "
error", unknown: "ERROR"}}
[error] 
[
{Ecto.Adapters.SQL, :execute_and_cache, 7, [file: 'lib/ecto/adapters/sql.ex', line: 405]}, 
{Ecto.Repo.Queryable, :execute, 5, [file: 'lib/ecto/repo/queryable.ex', line: 127]}, 
{Ecto.Repo.Queryable, :all, 4, [file: 'lib/ecto/repo/queryable.ex', line: 40]}, 
{ExAdminDemo.ExAdmin.Dashboard, :page_view, 1, [file: 'lib/ex_admin/page.ex', line: 14]}, 
{ExAdmin.AdminController, :dashboard, 2, [file: 'web/controllers/admin_controller.ex', line: 13]}, 
{ExAdmin.AdminController,:action, 2, [file: 'web/controllers/admin_controller.ex', line: 1]}, 
{ExAdmin.AdminController, :phoenix_controller_pipeline, 2, [file: 'web/controllers/admin_controller.ex', line: 1]}, 
{ExAdminDemo.Endpoint, :instrument, 4, [file: 'lib/ex_admin_demo/endpoint.ex', line: 1]}, 
{ExAdminDemo.Router, :dispatch, 2, [file: 'lib/phoenix/router.ex', line: 261]}, 
{ExAdminDemo.Router, :do_call, 2, [file: 'web/router.ex', line: 1]}, 
{ExAdminDemo.Endpoint, :phoenix_pipeline, 1, [file: 'lib/ex_admin_demo/endpoint.ex', line: 1]}, 
{ExAdminDemo.Endpoint, :"call (overridable 3)", 2, [file: 'lib/plug/debugger.ex', line: 93]}, 
{ExAdminDemo.Endpoint, :call, 2, [file: 'lib/ex_admin_demo/endpoint.ex', line: 1]}, 
{Plug.Adapters.Cowboy.Handler, :upgrade, 4, [file: 'lib/plug/adapters/cowboy/handler.ex', line: 15]}, 
{:cowboy_protocol, :execute, 4, [file: 'src/cowboy_protocol.erl', line: 442]}
]
[info] Sent 500 in 172ms
[error] #PID<0.401.0> running ExAdminDemo.Endpoint terminated
Server: localhost:4002 (http)
Request: GET /admin
*\* (exit) an exception was raised:
    *\* (Postgrex.Error) error (undefined_table): relation "orders" not exist
        (ecto) lib/ecto/adapters/sql.ex:405: Ecto.Adapters.SQL.execute_and_cache/7
        (ecto) lib/ecto/repo/queryable.ex:127: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
        (ex_admin_demo) lib/ex_admin/page.ex:14: ExAdminDemo.ExAdmin.Dashboard.page_view/1
        (ex_admin) web/controllers/admin_controller.ex:13: ExAdmin.AdminController.dashboard/2
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.action/2
        (ex_admin) web/controllers/admin_controller.ex:1: ExAdmin.AdminController.phoenix_controller_pipeline/2
        (ex_admin_demo) lib/ex_admin_demo/endpoint.ex:1: ExAdminDemo.Endpoint.instrument/4
        (ex_admin_demo) lib/phoenix/router.ex:261: ExAdminDemo.Router.dispatch/2
        (ex_admin_demo) web/router.ex:1: ExAdminDemo.Router.do_call/2
        (ex_admin_demo) lib/ex_admin_demo/endpoint.ex:1: ExAdminDemo.Endpoint.phoenix_pipeline/1
        (ex_admin_demo) lib/plug/debugger.ex:93: ExAdminDemo.Endpoint."call (overridable 3)"/2
        (ex_admin_demo) lib/ex_admin_demo/endpoint.ex:1: ExAdminDemo.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

**Comment by smpallen99** [comment]
Looks like a database issue. Were there any errors when you ran the mix tasks to create, migrate, and seed that database? Have you checked the database to see if the seed data is populated?
